name: Testing the output json
on:
 push:
  branches: [ main ]
 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set output
        id: set
        run: |
         echo ::set-output name=json_var::'[{ "name": "test", "client_payload": "111" }, { "name": "test2", "client_payload": "222" }] '
      - name: use output
        run: |
          echo $json_var | jq '.[].name'
        env:
          json_var: ${{ steps.set.outputs.json_var}}
