name: Testing the output json
on:
 push:
  branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set output
        id: set
        run: |
         #echo ::set-output name=json_var::'[{ "name": "test", "client_payload": "111" }, { "name": "test2", "client_payload": "222" }] '
         echo ::set-output name=json_var::'(curl --request GET --header "Authorization: Bearer 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" --header "Accept: application/vnd.github.v3+json" --url "https://api.github.com/orgs/internal-test-organization/members")'
         #env:
          #USER_TOKEN: ${{ secrets.PAGES_TOKEN }}
      - name: use output
        run: |
          echo $json_var | jq '.[].login'
        env:
          json_var: ${{ steps.set.outputs.json_var}}
